### ISSUE TITLE
panic when doing `dep init`

### ISSUE THREAD

**Issue by liusy182** [mattermost/mattermost-operator#129]
I am trying to follow the README.md to set up the dev environment. I am getting the a bunch of errors while doing `dep init` right before step `make dep`. One of them is:

```
panic: version queue is empty, should not happen: gopkg.in/fsnotify.v1

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc00059e000, 0xc001165220, 0xc0004ca9e0, 0x1, 0x1, 0x0, 0xc0004ca9e0)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/gps/solver.go:915 +0x55a
github.com/golang/dep/gps.(*solver).createVersionQueue(0xc00059e000, 0xc0004f31a0, 0x14, 0x0, 0x0, 0xc0004ca9e0, 0x1, 0x1, 0x0, 0x0, ...)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/gps/solver.go:902 +0x472
github.com/golang/dep/gps.(*solver).solve(0xc00059e000, 0x16e3660, 0xc0000b0058, 0x5, 0xc00055a708, 0xc0000ff698)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/gps/solver.go:505 +0x543
github.com/golang/dep/gps.(*solver).Solve(0xc00059e000, 0x16e3660, 0xc0000b0058, 0xc0001886f0, 0xc0000260c2, 0x29, 0xc000464bd0)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/gps/solver.go:440 +0x1eb
main.(*initCommand).Run(0xc00017768a, 0xc0000e8880, 0xc000188680, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/cmd/dep/init.go:155 +0x5ad
main.(*Config).Run(0xc0000bcea0, 0x0)
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/cmd/dep/main.go:212 +0x111c
main.main()
	/private/tmp/dep-20190614-48387-1iw5fry/src/github.com/golang/dep/cmd/dep/main.go:84 +0x636
```

Another overall question: should `Gopkg.toml` be checked in (currently it is missing)?

**Comment by gabrieljackson** [comment]
Thanks for bringing this to our attention @liusy182. We have moved to Go Modules and no longer use Dep, but our README and Makefile is out of date.

I will update both shortly.

**Comment by gabrieljackson** [comment]
@liusy182, I have updated the README for the operator. Please let us know if you have any further issues.
